#!/bin/bash
set -x
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
export BBPATH=$DIR/build

# check PATH (if rebooted after ./init)
if [[ ":$PATH:" != *"sources/poky/scripts"* ]]; then
	export PATH=$DIR/sources/poky/scripts:$PATH
fi

if [[ ":$PATH:" != *"sources/poky/bitbake/bin"* ]]; then
	export PATH=$DIR/sources/poky/bitbake/bin:$PATH
fi

echo "Started at $(date -u)" >> build.log
echo $PATH
bitbake fsl-image-qt5-validation-imx
if [ $? -ne 0 ]; then
	echo "Failed at $(date -u)" >> build.log
	exit 1
fi

rsync -av build/tmp/deploy/images/imx8mmevk/*.sdimg ../imx8mm/yocto/images
echo "Finished at $(date -u)" >> build.log
