#!/bin/bash

# get yocto
repo init -u https://source.codeaurora.org/external/imx/imx-manifest -b imx-linux-sumo -m imx-4.14.98-2.0.0_demo_mender.xml
repo sync
DISTRO=fsl-imx-xwayland MACHINE=imx8mmevk . fsl-setup-mender.sh -b build
cd ../
exit 0
# configure NFC
git clone https://github.com/NXPNFCLinux/meta-nxp-nfc.git sources/meta-nxp-nfc
patch build/tmp/work-shared/imx8mmevk/kernel-source/arch/arm64/boot/dts/freescale/fsl-imx8mm-evk.dts myextensions/nfc_pn7150/kernel_devices.patch
echo 'BBLAYERS += " ${BSPDIR}/sources/meta-nxp-nfc"' >> build/conf/bblayers.conf
echo 'IMAGE_INSTALL_append = " kernel-module-nxp-pn5xx nxp-nfc-bin "' >> build/conf/local.conf

# apply kernel config
cp myextensions/.config ./build/tmp/work/imx8mmevk-poky-linux/linux-imx/4.14.98-r0/build/.config # symlinks are not seen for bitbake...

# other changes
sed -E  "s/^.*MENDER_STORAGE_TOTAL_SIZE_MB.*/MENDER_STORAGE_TOTAL_SIZE_MB = 16384/" build/conf/local.conf # increase maximum image size
echo 'EXTRA_IMAGE_FEATURES = "debug-tweaks tools-debug tools-testapps"' >> build/conf/local.conf         # enable additional utils etc

